import {
  FileText, Search, PenTool, Languages, Palette, Video, Share2, TrendingUp, Mail, Users,
  ClipboardList, Target, BarChart3, Brain, Image as ImageIcon, Bug, Smartphone, Headphones, Code,
  Database, Briefcase, Camera, Mic, Music, BookOpen, Globe, Calculator, Home, Car, Heart,
  GraduationCap, Layout, Cloud, Shield, Wrench, DollarSign, Lightbulb, PieChart, MessageSquare,
  Zap, Cpu, ShoppingCart, Building, Film, Gamepad2, Truck, Coffee, Globe2, Bookmark, Key,
  FileCode, Server, SmartphoneCharging, CreditCard, Atom, FlaskConical, Scale, PaintBucket,
  Calendar, Gift, PhoneCall, Award, Package, DownloadCloud, UploadCloud, GitBranch,
  Terminal, FolderTree, Binary, Network, HardDrive, Router, Satellite,
  Wifi, Bluetooth, QrCode, Barcode, Scan, Fingerprint,
  Eye, Ear, Mic2, Volume2, Tv, MonitorSpeaker, Dice, Chess, Trophy,
  Navigation2, Compass, Map, MapPin, Navigation, Flag, Mountain,
  Tree, Leaf, Sprout, Flower, Sun, Moon, CloudRain, Wind, Thermometer, Droplets,
  Umbrella, Waves, Ship, Anchor, Plane, Rocket, Car as CarFront, Bike, Bus, Train, Ambulance,
  Stethoscope, Pill, HeartPulse, Bone, BrainCircuit, Dna, Microscope, TestTube, Beaker,
  Syringe, Bandage, Scalpel, Hospital, Bed, Bath, Sofa, Lamp, Armchair, Refrigerator,
  Microwave, Utensils, ChefHat, Wine, ShoppingBag, Tag, Percent, Receipt, Wallet,
  Banknote, Coins, Landmark, Factory, Warehouse, Construction, Hammer,
  Drill, Ruler, PaintRoller, Brush, Pencil, Highlighter, Eraser, Scissors,
  Paperclip, Link, Link2, Upload, Download, Copy, Filter,
  Sliders, Settings, Cog, Tool, Box, Forklift,
  Walk, Run, Dumbbell, Medal, Crown, Star, Sparkles,
  ThumbsUp, MessageCircle, Phone, Inbox, Send,
  Clock, Timer, AlarmClock, CalendarDays,
  ChartBar, ChartLine, ChartArea, ChartPie,
  TrendingDown, Activity, Pulse,
  TestTube2, Droplet,
  CloudOff, WifiOff, BluetoothConnected,
  Tablet, Laptop, Monitor, Printer, Scanner,
  Keyboard, Mouse, Speaker,
  Battery, BatteryCharging, Power,
  ShieldAlert, ShieldQuestion, ShieldX,
  Lock, Unlock, Eye as EyeIcon, EyeOff, Bell, BellRing,
  Megaphone, AlertCircle, AlertTriangle,
  Info, HelpCircle, CheckCircle,
  XCircle, Ban, CircleAlert,
  CircleCheck, CircleX, Circle,
  Square, Triangle, Hexagon,
  CircleDot, Dot, Plus, Minus,
  Divide, X, Equal, Infinity,
  Copyright, Registered, Trademark,
  Hash, AtSign, Asterisk, Pilcrow,
  Euro, Pound, Yen, Bitcoin,
  Gem, Diamond,
  Earth, CloudSun, Snowflake,
  Flame, Fish, Bird,
  Cat, Dog, Rabbit, Turtle, Whale,
  Bee, Spider, Butterfly,
  Snail, Footprints, Cactus, Volcano, Island, LifeBuoy, Swimming,
  Tennis, Basketball, Soccer, Football, Baseball, Hockey,
  Cricket, Golf, Boxing, Puzzle, Joystick,
  Headset, Radio, Podcast,
  Play, Pause, StopCircle, SkipBack, SkipForward,
  Repeat, Shuffle, ListMusic, ListVideo,
  Grid3x3, Columns, Rows,
  Sidebar, SidebarClose, PanelLeft,
  PanelTop, PanelRight, PanelBottom,
  Split, Combine, WrapText, AlignLeft,
  AlignCenter, AlignRight, AlignJustify,
  Bold, Italic, Underline, Strikethrough,
  Subscript, Superscript, List, ListOrdered,
  ListTodo, CheckSquare, Check,
  ChevronRight, ChevronLeft,
  ChevronUp, ChevronDown, ArrowRight,
  ArrowLeft, ArrowUp, ArrowDown,
  ArrowUpRight, ArrowDownRight,
  ArrowDownLeft, ArrowUpLeft,
  MoveRight, MoveLeft, MoveUp,
  MoveDown, RotateCw, RotateCcw,
  RefreshCw, RefreshCcw, ZoomIn,
  ZoomOut, Maximize, Minimize,
  Crop, Type, Sigma, Omega,
  MonitorSmartphone, Video as VideoIcon,
  FileEdit, ClipboardCheck,
  Water, Tractor, Wheat, Fuel, Gauge,
  Scroll, Vote,
  Health,
  Performance, Tutorial, Radar,
  TreePine, UserCheck, Shapes, ShoppingBasket,
  CheckCircle as CheckCircleIcon, MessageSquare as MessageSquareIcon,
  Target as TargetIcon, TrendingUp as TrendingUpIcon,
  User as UserIcon, File as FileIcon, Clipboard as ClipboardIcon,
  Camera as CameraIcon, Mic as MicIcon,
  DollarSign as DollarSignIcon, PieChart as PieChartIcon,
  MessageSquare as MessageSquareIcon2, Building as BuildingIcon,
  Lightbulb as LightbulbIcon, Zap as ZapIcon,
  Target as TargetIcon2, ChartLine as ChartLineIcon,
  Users as UsersIcon, Briefcase as BriefcaseIcon,
  Tag as TagIcon, Award as AwardIcon, Book as BookIcon,
  Globe as GlobeIcon, PenTool as PenToolIcon,
  Bookmark as BookmarkIcon, FileText as FileTextIcon,
  Highlighter as HighlighterIcon,
  BookOpen as BookOpenIcon, FileEdit as FileEditIcon,
  Languages as LanguagesIcon, Globe2 as Globe2Icon,
  Calculator as CalculatorIcon, Calendar as CalendarIcon,
  Phone as PhoneIcon, Gift as GiftIcon, Inbox as InboxIcon,
  Clock as ClockIcon, Mail as MailIcon,
  GraduationCap as GraduationCapIcon, Heart as HeartIcon,
  Home as HomeIcon, Car as CarIcon, Gamepad2 as GamepadIcon,
  Truck as TruckIcon, Coffee as CoffeeIcon,
  Stethoscope as StethoscopeIcon, Scale as ScaleIcon,
  Atom as AtomIcon, Flower as FlowerIcon,
  Plane as PlaneIcon, Ship as ShipIcon,
  BrainCircuit as BrainCircuitIcon,
  Eye as EyeIcon2, Ear as EarIcon,
  Search as SearchIcon, BarChart3 as BarChartIcon,
  FlaskConical as FlaskIcon,
  Link as LinkIcon, Shield as ShieldIcon,
  Wallet as WalletIcon, Gem as GemIcon,
  Coins as CoinsIcon, Lock as LockIcon,
  Music as MusicIcon, Volume2 as VolumeIcon,
  Radio as RadioIcon,
  TestTube as TestTubeIcon,
  CreditCard as CreditCardIcon,
  ChartLine as ChartLineIcon2,
  Banknote as BanknoteIcon,
  ChartBar as ChartBarIcon,
  Key as KeyIcon,
  Factory as FactoryIcon,
  HeartPulse as HeartPulseIcon,
  Pill as PillIcon, Dumbbell as DumbbellIcon,
  Microscope as MicroscopeIcon,
  Leaf as LeafIcon, CloudRain as CloudRainIcon,
  Wind as WindIcon, Recycle, Mountain as MountainIcon,
  Waves as WavesIcon, Sun as SunIcon,
  MapPin as MapPinIcon,
  Shirt, Scissors as ScissorsIcon,
  Star as StarIcon,
  Sprout as SproutIcon, Carrot, Cow,
  Droplet as DropletIcon,
  Wheat as WheatIcon,
  Apple, Trophy as TrophyIcon,
  Medal as MedalIcon,
  Timer as TimerIcon,
  HardDrive as HardDriveIcon,
  Droplet as DropletIcon2,
  Factory as FactoryIcon2, Satellite as SatelliteIcon2,
  Wrench as WrenchIcon, Plane as PlaneIcon2,
  Navigation as NavigationIcon2,
  Rocket as RocketIcon,
  Ship as ShipIcon2, Anchor as AnchorIcon,
  Fish as FishIcon, Navigation as NavigationIcon3,
  Radio as RadioIcon2, Package as PackageIcon,
  Brain as BrainIcon, Heart as HeartIcon2,
  MessageSquare as MessageSquareIcon3,
  BookOpen as BookOpenIcon2, Briefcase as BriefcaseIcon2,
  Church, Meditation, Globe as GlobeIcon2,
  Scroll as ScrollIcon,
  Megaphone as MegaphoneIcon,
  Shield as ShieldIcon2,
  ChartLine as ChartLineIcon3,
  Vote as VoteIcon,
  Brush as BrushIcon,
  Theater, Music as MusicIcon2,
  Cpu as CpuIcon, Cloud as CloudIcon,
  Database as DatabaseIcon, Network as NetworkIcon,
  Server as ServerIcon, Code as CodeIcon,
  Telescope, Planet, Orbit, Meteor,
  TrafficCone,
  Utensils as UtensilsIcon,
  Lamp as LampIcon,
  Bath as BathIcon, Bed as BedIcon,
  Cctv, Dog as DogIcon, Cat as CatIcon,
  Bird as BirdIcon, Fish as FishIcon2,
  Bone as BoneIcon,
  Gauge as GaugeIcon, Fuel as FuelIcon,
  Bike as BikeIcon,
  Calendar as CalendarIcon2,
  Music as MusicIcon3,
  Camera as CameraIcon2,
  Target as TargetIcon3, Briefcase as BriefcaseIcon3,
  ChartLine as ChartLineIcon4,
  Database as DatabaseIcon2,
  Network as NetworkIcon2,
  PieChart as PieChartIcon2,
  Binary as BinaryIcon,
  ShieldCheck, ShoppingCart as ShoppingCartIcon,
  Globe as GlobeIcon3,
  Phone as PhoneIcon2, Video as VideoIcon2,
  Users as UsersIcon2, HelpCircle as HelpCircleIcon,
  Tutorial as TutorialIcon, Shield as ShieldIcon3,
  Calendar as CalendarIcon3, DollarSign as DollarSignIcon2,
  Users as UsersIcon3, Building as BuildingIcon2,
  TrendingUp as TrendingUpIcon2,
  Lightbulb as LightbulbIcon2,
  Globe as GlobeIcon4,
  BarChart3 as BarChartIcon2,
  TestTube as TestTubeIcon2,
  VirtualReality, Layout as LayoutIcon,
  Palette as PaletteIcon,
  Factory as FactoryIcon3,
  Heart as HeartIcon3,
  Home as HomeIcon2,
  AlertTriangle as AlertTriangleIcon,
  Shield as ShieldIcon4,
  Smartphone as SmartphoneIcon,
  Gamepad2 as Gamepad2Icon,
  BookOpen as BookOpenIcon3,
  Mail as MailIcon2,
  Video as VideoIcon3,
  Database as DatabaseIcon3,
  Database as DatabaseIcon4,
  Database as DatabaseIcon5,
  Database as DatabaseIcon6,
  Database as DatabaseIcon7,
  Database as DatabaseIcon8,
  Database as DatabaseIcon9,
  Router as RouterIcon,
  Wifi as WifiIcon,
  Server as ServerIcon2,
  Cloud as CloudIcon2,
  Zap as ZapIcon2,
  Monitor as MonitorIcon,
  Home as HomeIcon3,
  Calendar as CalendarIcon4,
  Clipboard as ClipboardIcon2,
  Kanban, Waterfall,
  Users as UsersIcon4,
  Clock as ClockIcon2,
  AlertTriangle as AlertTriangleIcon2
} from "lucide-react";

const CategoriesSection = () => {
  const categories = [
    // Original categories (20)
    { icon: FileText, name: "Data Entry", jobs: 245, color: "from-blue-500/20 to-blue-600/20" },
    { icon: Search, name: "Web Research", jobs: 189, color: "from-purple-500/20 to-purple-600/20" },
    { icon: PenTool, name: "Content Writing", jobs: 312, color: "from-pink-500/20 to-pink-600/20" },
    { icon: Languages, name: "Translation", jobs: 156, color: "from-green-500/20 to-green-600/20" },
    { icon: Palette, name: "Graphic Design", jobs: 278, color: "from-orange-500/20 to-orange-600/20" },
    { icon: Video, name: "Video Editing", jobs: 134, color: "from-red-500/20 to-red-600/20" },
    { icon: Share2, name: "Social Media", jobs: 223, color: "from-cyan-500/20 to-cyan-600/20" },
    { icon: TrendingUp, name: "SEO Tasks", jobs: 167, color: "from-lime-500/20 to-lime-600/20" },
    { icon: Mail, name: "Email Marketing", jobs: 98, color: "from-amber-500/20 to-amber-600/20" },
    { icon: Users, name: "Virtual Assistance", jobs: 345, color: "from-teal-500/20 to-teal-600/20" },
    { icon: ClipboardList, name: "Product Listing", jobs: 187, color: "from-indigo-500/20 to-indigo-600/20" },
    { icon: Target, name: "Lead Generation", jobs: 145, color: "from-rose-500/20 to-rose-600/20" },
    { icon: BarChart3, name: "Surveys", jobs: 234, color: "from-violet-500/20 to-violet-600/20" },
    { icon: Brain, name: "AI Data Labeling", jobs: 412, color: "from-emerald-500/20 to-emerald-600/20" },
    { icon: ImageIcon, name: "Image Annotation", jobs: 289, color: "from-sky-500/20 to-sky-600/20" },
    { icon: Bug, name: "Software Testing", jobs: 167, color: "from-fuchsia-500/20 to-fuchsia-600/20" },
    { icon: Smartphone, name: "UX Feedback", jobs: 123, color: "from-yellow-500/20 to-yellow-600/20" },
    { icon: Headphones, name: "Customer Support", jobs: 198, color: "from-slate-500/20 to-slate-600/20" },
    { icon: Code, name: "Copywriting", jobs: 267, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Database, name: "Transcription", jobs: 178, color: "from-purple-500/20 to-pink-600/20" },
    
    // Technical & Development (20)
    { icon: Code, name: "Web Development", jobs: 432, color: "from-blue-600/20 to-indigo-600/20" },
    { icon: Smartphone, name: "App Development", jobs: 289, color: "from-purple-600/20 to-pink-600/20" },
    { icon: FileCode, name: "Frontend Development", jobs: 321, color: "from-cyan-500/20 to-blue-600/20" },
    { icon: Server, name: "Backend Development", jobs: 298, color: "from-green-600/20 to-emerald-600/20" },
    { icon: Database, name: "Database Management", jobs: 187, color: "from-orange-500/20 to-red-600/20" },
    { icon: Cloud, name: "Cloud Computing", jobs: 156, color: "from-sky-500/20 to-blue-600/20" },
    { icon: Shield, name: "Cybersecurity", jobs: 134, color: "from-red-500/20 to-rose-600/20" },
    { icon: Cpu, name: "DevOps", jobs: 112, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: GitBranch, name: "Git Management", jobs: 89, color: "from-orange-500/20 to-amber-600/20" },
    { icon: Terminal, name: "Scripting", jobs: 156, color: "from-green-500/20 to-lime-600/20" },
    { icon: FolderTree, name: "File Organization", jobs: 134, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Binary, name: "Algorithm Design", jobs: 112, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: Network, name: "Networking", jobs: 145, color: "from-red-500/20 to-orange-600/20" },
    { icon: HardDrive, name: "Data Storage", jobs: 123, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Router, name: "Network Security", jobs: 98, color: "from-teal-500/20 to-green-600/20" },
    { icon: Satellite, name: "Satellite Systems", jobs: 67, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Wifi, name: "Wireless Networks", jobs: 89, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Bluetooth, name: "Bluetooth Tech", jobs: 78, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: QrCode, name: "Security Systems", jobs: 112, color: "from-gray-500/20 to-slate-600/20" },
    { icon: Radio, name: "Radio Systems", jobs: 56, color: "from-amber-500/20 to-yellow-600/20" },
    
    // Creative & Design (15)
    { icon: Camera, name: "Photography", jobs: 178, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Mic, name: "Voice Over", jobs: 145, color: "from-pink-500/20 to-rose-600/20" },
    { icon: Music, name: "Music Production", jobs: 98, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Layout, name: "UI/UX Design", jobs: 267, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: PaintBucket, name: "Illustration", jobs: 189, color: "from-orange-500/20 to-yellow-600/20" },
    { icon: BookOpen, name: "Proofreading", jobs: 167, color: "from-emerald-500/20 to-green-600/20" },
    { icon: Film, name: "Animation", jobs: 123, color: "from-red-500/20 to-orange-600/20" },
    { icon: Video, name: "Video Production", jobs: 156, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Music, name: "Sound Design", jobs: 89, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Palette, name: "Color Theory", jobs: 67, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Type, name: "Typography", jobs: 78, color: "from-orange-500/20 to-red-600/20" },
    { icon: Scissors, name: "Video Editing", jobs: 112, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Grid3x3, name: "Layout Design", jobs: 134, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: Ruler, name: "Precision Design", jobs: 89, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Brush, name: "Digital Painting", jobs: 156, color: "from-pink-500/20 to-rose-600/20" },
    
    // Business & Marketing (15)
    { icon: DollarSign, name: "Financial Analysis", jobs: 156, color: "from-green-500/20 to-emerald-600/20" },
    { icon: PieChart, name: "Data Analysis", jobs: 234, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: MessageSquare, name: "Business Consulting", jobs: 145, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Building, name: "Project Management", jobs: 198, color: "from-orange-500/20 to-amber-600/20" },
    { icon: ShoppingCart, name: "E-commerce Management", jobs: 167, color: "from-teal-500/20 to-green-600/20" },
    { icon: Lightbulb, name: "Business Planning", jobs: 123, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Zap, name: "Digital Marketing", jobs: 345, color: "from-red-500/20 to-pink-600/20" },
    { icon: Target, name: "Brand Strategy", jobs: 112, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: ChartLine, name: "Market Research", jobs: 189, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Megaphone, name: "Public Relations", jobs: 134, color: "from-orange-500/20 to-yellow-600/20" },
    { icon: Users, name: "HR Consulting", jobs: 156, color: "from-green-500/20 to-lime-600/20" },
    { icon: Briefcase, name: "Corporate Training", jobs: 89, color: "from-purple-500/20 to-violet-600/20" },
    { icon: TrendingUp, name: "Sales Strategy", jobs: 178, color: "from-red-500/20 to-pink-600/20" },
    { icon: Tag, name: "Pricing Strategy", jobs: 123, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: Award, name: "Quality Management", jobs: 156, color: "from-amber-500/20 to-orange-600/20" },
    
    // Writing & Translation (15)
    { icon: BookOpen, name: "Technical Writing", jobs: 189, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Globe, name: "Transcreation", jobs: 134, color: "from-blue-500/20 to-sky-600/20" },
    { icon: PenTool, name: "Script Writing", jobs: 145, color: "from-emerald-500/20 to-teal-600/20" },
    { icon: Bookmark, name: "Ghostwriting", jobs: 112, color: "from-gray-500/20 to-slate-600/20" },
    { icon: FileText, name: "Resume Writing", jobs: 178, color: "from-amber-500/20 to-yellow-600/20" },
    { icon: PenTool, name: "Creative Writing", jobs: 234, color: "from-pink-500/20 to-rose-600/20" },
    { icon: Highlighter, name: "Editing", jobs: 189, color: "from-green-500/20 to-emerald-600/20" },
    { icon: FileText, name: "Academic Writing", jobs: 156, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: Newspaper, name: "Journalism", jobs: 123, color: "from-orange-500/20 to-red-600/20" },
    { icon: BookOpen, name: "Book Writing", jobs: 89, color: "from-purple-500/20 to-violet-600/20" },
    { icon: MessageSquare, name: "Speech Writing", jobs: 67, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: FileEdit, name: "Grant Writing", jobs: 112, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Languages, name: "Localization", jobs: 145, color: "from-red-500/20 to-pink-600/20" },
    { icon: Globe2, name: "Cultural Consulting", jobs: 78, color: "from-green-500/20 to-lime-600/20" },
    { icon: CheckCircle, name: "Fact Checking", jobs: 134, color: "from-blue-500/20 to-sky-600/20" },
    
    // Administrative (10)
    { icon: Calculator, name: "Accounting", jobs: 156, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Calendar, name: "Calendar Management", jobs: 123, color: "from-red-500/20 to-rose-600/20" },
    { icon: PhoneCall, name: "Telemarketing", jobs: 134, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Gift, name: "Event Planning", jobs: 145, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Inbox, name: "Email Management", jobs: 178, color: "from-orange-500/20 to-amber-600/20" },
    { icon: Clock, name: "Time Management", jobs: 156, color: "from-teal-500/20 to-green-600/20" },
    { icon: FileText, name: "Documentation", jobs: 189, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: ClipboardCheck, name: "Task Management", jobs: 134, color: "from-red-500/20 to-orange-600/20" },
    { icon: Mail, name: "Correspondence", jobs: 112, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Users, name: "Recruitment", jobs: 156, color: "from-green-500/20 to-lime-600/20" },
    
    // Specialized & Niche (15)
    { icon: GraduationCap, name: "Tutoring", jobs: 189, color: "from-orange-500/20 to-amber-600/20" },
    { icon: Heart, name: "Health & Wellness", jobs: 167, color: "from-pink-500/20 to-rose-600/20" },
    { icon: Home, name: "Interior Design", jobs: 123, color: "from-yellow-500/20 to-orange-600/20" },
    { icon: Car, name: "AutoCAD Design", jobs: 112, color: "from-teal-500/20 to-green-600/20" },
    { icon: Gamepad2, name: "Game Development", jobs: 145, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Truck, name: "Supply Chain", jobs: 134, color: "from-gray-500/20 to-slate-600/20" },
    { icon: Coffee, name: "Food Services", jobs: 89, color: "from-amber-500/20 to-yellow-600/20" },
    { icon: Globe2, name: "Travel Planning", jobs: 78, color: "from-emerald-500/20 to-teal-600/20" },
    { icon: Stethoscope, name: "Medical Writing", jobs: 112, color: "from-red-500/20 to-pink-600/20" },
    { icon: Scale, name: "Legal Research", jobs: 89, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: Atom, name: "Scientific Consulting", jobs: 67, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Flower, name: "Environmental Consulting", jobs: 78, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: Plane, name: "Aviation Consulting", jobs: 45, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Ship, name: "Maritime Consulting", jobs: 34, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Building, name: "Architectural Design", jobs: 89, color: "from-orange-500/20 to-red-600/20" },
    
    // AI & Machine Learning (10)
    { icon: BrainCircuit, name: "AI Development", jobs: 245, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Cpu, name: "ML Model Training", jobs: 189, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Binary, name: "Algorithm Development", jobs: 156, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Brain, name: "Neural Networks", jobs: 112, color: "from-red-500/20 to-orange-600/20" },
    { icon: Network, name: "Robotics", jobs: 89, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Eye, name: "Computer Vision", jobs: 134, color: "from-teal-500/20 to-green-600/20" },
    { icon: Ear, name: "Speech Recognition", jobs: 112, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: ChartLine, name: "Predictive Analytics", jobs: 156, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Network, name: "Deep Learning", jobs: 123, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Dna, name: "Bioinformatics", jobs: 89, color: "from-green-500/20 to-lime-600/20" },
    
    // Research & Analysis (10)
    { icon: Search, name: "Market Analysis", jobs: 178, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: BarChart3, name: "Statistical Analysis", jobs: 145, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Microscope, name: "Scientific Research", jobs: 112, color: "from-red-500/20 to-pink-600/20" },
    { icon: FlaskConical, name: "Lab Research", jobs: 89, color: "from-purple-500/20 to-violet-600/20" },
    { icon: BookOpen, name: "Literature Review", jobs: 134, color: "from-orange-500/20 to-amber-600/20" },
    { icon: Globe, name: "Geographic Analysis", jobs: 78, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: PieChart, name: "Economic Research", jobs: 112, color: "from-yellow-500/20 to-yellow-600/20" },
    { icon: Map, name: "Demographic Analysis", jobs: 89, color: "from-blue-500/20 to-sky-600/20" },
    { icon: TrendingUp, name: "Trend Analysis", jobs: 156, color: "from-green-500/20 to-lime-600/20" },
    { icon: Target, name: "Competitive Analysis", jobs: 123, color: "from-red-500/20 to-orange-600/20" },
    
    // Crypto & Blockchain (10)
    { icon: Bitcoin, name: "Blockchain Development", jobs: 189, color: "from-orange-500/20 to-yellow-600/20" },
    { icon: Link, name: "Smart Contracts", jobs: 145, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Shield, name: "Crypto Security", jobs: 112, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Wallet, name: "Wallet Development", jobs: 89, color: "from-purple-500/20 to-pink-600/20" },
    { icon: ChartLine, name: "Crypto Analysis", jobs: 156, color: "from-red-500/20 to-rose-600/20" },
    { icon: Network, name: "DeFi Development", jobs: 134, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Gem, name: "NFT Development", jobs: 178, color: "from-teal-500/20 to-green-600/20" },
    { icon: Coins, name: "Tokenomics", jobs: 112, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Code, name: "dApp Development", jobs: 156, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Lock, name: "Crypto Audit", jobs: 89, color: "from-green-500/20 to-lime-600/20" },
    
    // Education & Training (10)
    { icon: GraduationCap, name: "Online Tutoring", jobs: 234, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: BookOpen, name: "Course Creation", jobs: 189, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Video, name: "Educational Videos", jobs: 156, color: "from-red-500/20 to-pink-600/20" },
    { icon: Users, name: "Workshop Facilitation", jobs: 123, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Mic, name: "Public Speaking", jobs: 89, color: "from-orange-500/20 to-amber-600/20" },
    { icon: PenTool, name: "Curriculum Design", jobs: 112, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: Target, name: "Test Preparation", jobs: 178, color: "from-yellow-500/20 to-yellow-600/20" },
    { icon: CheckCircle, name: "Assessment Design", jobs: 134, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Globe, name: "Language Instruction", jobs: 156, color: "from-green-500/20 to-lime-600/20" },
    { icon: Brain, name: "Cognitive Training", jobs: 112, color: "from-red-500/20 to-orange-600/20" },
    
    // Music & Audio (10)
    { icon: Music, name: "Music Composition", jobs: 156, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Headphones, name: "Audio Editing", jobs: 134, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Volume2, name: "Sound Engineering", jobs: 112, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Mic, name: "Podcast Production", jobs: 189, color: "from-red-500/20 to-rose-600/20" },
    { icon: Music, name: "Jingle Creation", jobs: 89, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Video, name: "Audio for Video", jobs: 123, color: "from-teal-500/20 to-green-600/20" },
    { icon: Radio, name: "Radio Production", jobs: 78, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: Music, name: "Music Theory", jobs: 67, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Headphones, name: "Audio Restoration", jobs: 89, color: "from-green-500/20 to-lime-600/20" },
    { icon: Mic, name: "Voice Coaching", jobs: 112, color: "from-red-500/20 to-orange-600/20" },
    
    // Gaming & Esports (10)
    { icon: Gamepad2, name: "Game Design", jobs: 178, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Code, name: "Game Programming", jobs: 156, color: "from-blue-500/20 to-cyan-600/20" },
    { icon: Palette, name: "Game Art", jobs: 134, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Music, name: "Game Audio", jobs: 112, color: "from-red-500/20 to-pink-600/20" },
    { icon: Trophy, name: "Esports Coaching", jobs: 89, color: "from-indigo-500/20 to-purple-600/20" },
    { icon: Video, name: "Game Streaming", jobs: 145, color: "from-teal-500/20 to-green-600/20" },
    { icon: PenTool, name: "Game Writing", jobs: 123, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: TestTube, name: "Game Testing", jobs: 156, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Puzzle, name: "Puzzle Design", jobs: 89, color: "from-green-500/20 to-lime-600/20" },
    { icon: Target, name: "Level Design", jobs: 112, color: "from-red-500/20 to-orange-600/20" },
    
    // Finance & Trading (10)
    { icon: CreditCard, name: "Bookkeeping", jobs: 156, color: "from-green-500/20 to-lime-600/20" },
    { icon: TrendingUp, name: "Stock Trading", jobs: 134, color: "from-red-500/20 to-orange-600/20" },
    { icon: ChartLine, name: "Forex Trading", jobs: 189, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: DollarSign, name: "Tax Preparation", jobs: 112, color: "from-green-500/20 to-emerald-600/20" },
    { icon: PieChart, name: "Investment Analysis", jobs: 145, color: "from-red-500/20 to-pink-600/20" },
    { icon: Calculator, name: "Financial Modeling", jobs: 123, color: "from-purple-500/20 to-violet-600/20" },
    { icon: Wallet, name: "Wealth Management", jobs: 89, color: "from-orange-500/20 to-amber-600/20" },
    { icon: Banknote, name: "Risk Assessment", jobs: 112, color: "from-teal-500/20 to-cyan-600/20" },
    { icon: Coins, name: "Commodity Trading", jobs: 78, color: "from-yellow-500/20 to-yellow-600/20" },
    { icon: ChartBar, name: "Portfolio Management", jobs: 134, color: "from-blue-500/20 to-sky-600/20" },
    
    // Legal & Compliance (10)
    { icon: Scale, name: "Legal Services", jobs: 145, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: Key, name: "Real Estate", jobs: 167, color: "from-green-500/20 to-emerald-600/20" },
    { icon: FileText, name: "Contract Review", jobs: 189, color: "from-red-500/20 to-orange-600/20" },
    { icon: Shield, name: "Compliance", jobs: 134, color: "from-purple-500/20 to-pink-600/20" },
    { icon: Search, name: "Due Diligence", jobs: 112, color: "from-teal-500/20 to-green-600/20" },
    { icon: BookOpen, name: "Legal Research", jobs: 156, color: "from-yellow-500/20 to-amber-600/20" },
    { icon: FileEdit, name: "Policy Writing", jobs: 123, color: "from-blue-500/20 to-sky-600/20" },
    { icon: Scale, name: "Dispute Resolution", jobs: 89, color: "from-green-500/20 to-lime-600/20" },
    { icon: Shield, name: "Regulatory Affairs", jobs: 112, color: "from-red-500/20 to-rose-600/20" },
    { icon: ClipboardCheck, name: "Audit Preparation", jobs: 145, color: "from-indigo-500/20 to-purple-600/20" },
    
    // Logistics & Operations (10)
    { icon: Package, name: "Inventory Management", jobs: 145, color: "from-amber-500/20 to-orange-600/20" },
    { icon: UploadCloud, name: "Data Migration", jobs: 112, color: "from-cyan-500/20 to-blue-600/20" },
    { icon: DownloadCloud, name: "Backup Solutions", jobs: 98, color: "from-teal-500/20 to-green-600/20" },
    { icon: Truck, name: "Logistics Planning", jobs: 134, color: "from-gray-500/20 to-slate-600/20" },
    { icon: Warehouse, name: "Warehouse Management", jobs: 89, color: "from-blue-500/20 to-indigo-600/20" },
    { icon: Ship, name: "Shipping Coordination", jobs: 112, color: "from-green-500/20 to-emerald-600/20" },
    { icon: Factory, name: "Production Planning", jobs: 78, color: "from-red-500/20 to-pink-600/20" },
    { icon: ClipboardList, name: "Procurement", jobs: 123, color: "from-purple-500/20 to-violet-600/20" },
    { icon: BarChart3, name: "Operations Analysis", jobs: 89, color: "from-orange-500/20 to-amber-600/20" },
    { icon: Users, name: "Team Coordination", jobs: 156, color: "from-teal-500/20 to-cyan-600/20" },
  ];

  return (
    <section id="categories" className="py-24 lg:py-32 relative">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6">
            <span className="text-sm text-primary font-medium">Job Categories</span>
            <span className="text-xs bg-primary text-primary-foreground px-2 py-1 rounded-full">
              {categories.length}+ Categories
            </span>
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-6">
            <span className="gradient-text">Comprehensive Range</span> of Freelance Work
          </h2>
          <p className="text-lg text-muted-foreground">
            From creative design to technical development, find work across {categories.length}+ categories matching your expertise
          </p>
        </div>

        {/* Categories Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-4">
          {categories.map((category, index) => (
            <div
              key={index}
              className="group glass-card-hover p-5 cursor-pointer hover:shadow-lg transition-all duration-300"
            >
              <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${category.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300`}>
                <category.icon className="w-6 h-6 text-foreground group-hover:scale-125 transition-transform" />
              </div>
              <h3 className="font-semibold text-foreground mb-1 group-hover:text-primary transition-colors line-clamp-2">
                {category.name}
              </h3>
              <p className="text-sm text-muted-foreground">
                {category.jobs.toLocaleString()} jobs
              </p>
            </div>
          ))}
        </div>

        {/* View More Button */}
        <div className="text-center mt-12">
          <button className="px-8 py-3 rounded-full bg-gradient-to-r from-primary to-primary/80 text-primary-foreground font-medium hover:shadow-lg hover:shadow-primary/20 transition-all duration-300 hover:scale-105">
            View All Categories
          </button>
        </div>
      </div>
    </section>
  );
};

export default CategoriesSection;